### ISSUE TITLE
Wifite 2 (r87) is not running, refers problems inside wifite and subprocess.py

### ISSUE THREAD

**Issue by doctorized** [derv82/wifite#111]
I have installed Kali linux 2017.1 x86 light. I have ran "apt-get update", "apt-get upgrade" and "apt-get install kali-linux-wireless". Wifite keeps saying the following. How can I fix it?
`[+] scanning for wireless devices...`
`Traceback (most recent call last):`
`File "/usr/bin/wifite", line 3462, in <module>`
`engine.Start()`
`File "/usr/bin/wifite", line 1313, in Start`
`self.RUN_CONFIG.THIS_MAC = get_mac_address(iface) # Store current MAC address`
`File "/usr/bin/wifite", line 1864, in get_mac_address`
`proc = Popen(['ifconfig', iface], stdout=PIPE, stderr=DN)`
`File "/usr/lib/python2.7/subprocess.py", line 390, in __init__`
`errread, errwrite)`
`File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child`
`raise child_exception`
`OSError: [Errno 2] No such file or directory`

**Comment by MisterBianco** [comment]
The problem is the Popen command in the subprocess module can't pass args with an arg of:

shell=True

Can you explain exactly how to reproduce this?

**Comment by doctorized** [comment]
I installed Kali 2017.1 x86 light. I usedba HP 620 laptop with the built-in wireless card. I installed wifite. It said some packages, like reaver and cowpatty, should be installed. I installed all of them. I ran wifite again and these errors occurred.  I ran "apt-get update", "apt-get upgrade" and apt-get install wireless" but they didn't help. So, I formatted my hard drive and installed the full version of Kali x86 2017.1. Since then, wifitevruns with no problem but it fails to crack any network. It says it failed and quits.

**Comment by doctorized** [comment]
In the first line I wanted to write "used a". D was added accidently.

**Comment by Thecave3** [comment]
I have the same issue, just after the download on wifite on debian 9 I tried to run it and get the same error.
aircrack-ng is installed, reaver and pyrit are not.

I truly think that this issue could be related to the fact that now debian 9 uses "ip" instead of "ifconfig"
so when the code tries to launch ifconfig with 
`proc = Popen(['ifconfig', iface], stdout=PIPE, stderr=DN)`
it returns the error 

> OSError: [Errno 2] No such file or directory

This could be also the problem of issue #70 since the error traceback is the same. 
A possible solution could be a catch to this specific error and if the os is something like debian (and uses "ip" command) then try to call the popen on "ip"

**Comment by Thecave3** [comment]
All these issues are resolved in [wifite2](https://github.com/derv82/wifite2/) so it is useless to search further: just switch to the newer one

**Comment by ALzaem1991** [comment]
كيف يتم تحميل الادوات


لاني عكزت عن ايجاد حل
لتحميل الادوات
