### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by morteryler** [derv82/wifite#124]
I intercepted the handshake and it survived, and then the error got out:
`Traceback (most recent call last):
  File "/bin/wifite", line 3536, in <module>
    engine.Start()
  File "/bin/wifite", line 1465, in Start
    if wpa_attack.RunAttack():
  File "/bin/wifite", line 2151, in RunAttack
    self.wpa_get_handshake()
  File "/bin/wifite", line 2293, in wpa_get_handshake
    if self.RUN_CONFIG.WPA_STRIP_HANDSHAKE: self.strip_handshake(save_as)
  File "/bin/wifite", line 2555, in strip_handshake
    rename(capfile + '.temp', output_file)
  File "/bin/wifite", line 1656, in rename
    os.rename(old, new)
OSError: [Errno 2] No such file or directory`

**Comment by islamux** [comment]
The same problem with me in blackarch 
Linux BlackArch 4.18.9-arch1-1-ARCH #1 SMP PREEMPT

**Comment by islamux** [comment]
The same problem with me in blackarch

uname -a 
Linux BlackArch 4.18.9-arch1-1-ARCH #1 SMP PREEMPT
