### ISSUE TITLE
wifite can't lunch handshake attck

### ISSUE THREAD

**Issue by MAX-RAY** [derv82/wifite#141]
Wifite can scan network but cant lunch attack.

`Traceback (most recent call last):
  File "/usr/bin/wifite", line 3536, in <module>
    engine.Start()
  File "/usr/bin/wifite", line 1456, in Start
    need_handshake = not wps_attack.RunAttack()
  File "/usr/bin/wifite", line 3237, in RunAttack
    if self.attack_wps_pixie():
  File "/usr/bin/wifite", line 3372, in attack_wps_pixie
    os.remove(self.RUN_CONFIG.temp + "out.out")
OSError: [Errno 2] No such file or directory: '/tmp/wifiteBdpJ9V/out.out'
`

**Comment by darknotevil** [comment]
> Wifite can scan network but cant lunch attack.
> 
> `Traceback (most recent call last): File "/usr/bin/wifite", line 3536, in <module> engine.Start() File "/usr/bin/wifite", line 1456, in Start need_handshake = not wps_attack.RunAttack() File "/usr/bin/wifite", line 3237, in RunAttack if self.attack_wps_pixie(): File "/usr/bin/wifite", line 3372, in attack_wps_pixie os.remove(self.RUN_CONFIG.temp + "out.out") OSError: [Errno 2] No such file or directory: '/tmp/wifiteBdpJ9V/out.out' `

Hello. Have you found a solution? I have the same problem.

**Comment by y0d4a** [comment]
same here from manjaro...
