### ISSUE TITLE
Missing dependency... maybe?

### ISSUE THREAD

**Issue by nhockey** [derv82/wifite#70]
I simply can not figure out what program it's not finding, they all exist in roots path. Im not a python kinda guy, so i'm having an issue tracking it down.

```
Traceback (most recent call last):
  File "/usr/bin/wifite", line 4483, in <module>
    if not engine.programs_check():  # Ensure required programs are installed.
  File "/usr/bin/wifite", line 1033, in programs_check
    if file_search(p):
  File "/usr/bin/wifite", line 2728, in file_search
    proc = Popen([searcher[0], searcher[1] + program + searcher[2]], stdout=PIPE, stderr=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by nhockey** [comment]
by the way it's on version "WiFite v2 (r103)" on Arch Linux with python 2.7.11

**Comment by tomtox** [comment]
Bin Linux Anfänger könntest du mir den link für archlinux wifite v2 2.7.11 schicken ? Suche Linux Mentor bin für jede gute Idee zu haben
