### ISSUE TITLE
UnboundLocalError: local variable 'old_mac' referenced before assignment

### ISSUE THREAD

**Issue by lansman** [derv82/wifite#76]
WiFite v2 (r87)

File "/usr/bin/wifite", line 1985 in mac_anonymize
  RUN_CONFIG.ORIGINAL_IFACE_MAC = (iface, old_mac)

**Comment by HendrikF** [comment]
Same Problem here.

```
root@raspberrypi:~# ./wifite.py -i wlan0 -mac

  .;'                     `;,
 .;'  ,;'             `;,  `;,   WiFite v2 (r87)
.;'  ,;'  ,;'     `;,  `;,  `;,
::   ::   :   ( )   :   ::   ::  automated wireless auditor
':.  ':.  ':. /_\ ,:'  ,:'  ,:'
 ':.  ':.    /___\    ,:'  ,:'   designed for Linux
  ':.       /_____\      ,:'
           /       \

 [+] mac address anonymizing enabled
      not: only works if device is not already in monitor mode!
 [+] set interface :wlan0

 [!] the program reaver is required for WPS attacks
       available at http://code.google.com/p/reaver-wps
 [!] the program tshark is not required, but is recommended
 [!] the program pyrit is not required, but is recommended
 [!] the program cowpatty is not required, but is recommended

 [+] scanning for wireless devices...
 [!] could not find wireless interface "wlan0" in monitor mode
 [+] changing wlan0's MAC from **:9a to **:97... done
 [+] enabling monitor mode on wlan0... done
Traceback (most recent call last):
  File "./wifite.py", line 3525, in <module>
    engine.Start()
  File "./wifite.py", line 1383, in Start
    iface = self.get_iface()
  File "./wifite.py", line 995, in get_iface
    return self.enable_monitor_mode(self.RUN_CONFIG.WIRELESS_IFACE)
  File "./wifite.py", line 894, in enable_monitor_mode
    self.RUN_CONFIG.IFACE_TO_TAKE_DOWN = self.get_iface()
  File "./wifite.py", line 1032, in get_iface
    return self.enable_monitor_mode(monitor)
  File "./wifite.py", line 888, in enable_monitor_mode
    mac_anonymize(iface)
  File "./wifite.py", line 1980, in mac_anonymize
    RUN_CONFIG.ORIGINAL_IFACE_MAC = (iface, old_mac)
UnboundLocalError: local variable 'old_mac' referenced before assignment
```

**Comment by HendrikF** [comment]
The Error does not appear, when I leave mac anon turned off:

```
root@raspberrypi:~# ./wifite.py

  .;'                     `;,
 .;'  ,;'             `;,  `;,   WiFite v2 (r87)
.;'  ,;'  ,;'     `;,  `;,  `;,
::   ::   :   ( )   :   ::   ::  automated wireless auditor
':.  ':.  ':. /_\ ,:'  ,:'  ,:'
 ':.  ':.    /___\    ,:'  ,:'   designed for Linux
  ':.       /_____\      ,:'
           /       \


 [!] the program cowpatty is not required, but is recommended

 [+] scanning for wireless devices...
 [+] enabling monitor mode on null... done
 [+] enabling monitor mode on null... done
 [+] enabling monitor mode on null... done
 [+] enabling monitor mode on null... done
 [+] enabling monitor mode on null... done
 [+] enabling monitor mode on null...^C
 (^C) interrupted

 [+] quitting
```

Has it something to do with the `null` in the above output?
Maybe it does not find a device. I am too unexperienced to tell.

**Comment by BL4ckR0se** [comment]
Man yall muthafuckas be wastin ppls time with these n00b ass mistakes. 

We aint got time for this kiddie-proofin bullshit, son! Ill tell yall how to fix this shit now FIX THE GODDAMN SHIT 

(starting line 1021:)
if len(monitors) == 0:
            print R + ' [!]' + O + " no wireless interfaces were found." + W
            print R + ' [!]' + O + " you need to plug in a wifi device or install drivers.\n" + W
            self.RUN_CONFIG.exit_gracefully(0)
        elif self.RUN_CONFIG.WIRELESS_IFACE != '' and monitors.count(self.RUN_CONFIG.WIRELESS_IFACE) > 0:
            monitor = monitors[0][:monitors[0].find('\t')]
			if monitor.startswith('phy'): monitor = monitors[0].split()[1] <-- yall forgot to put this line here, noob ass bitch!
            return self.enable_monitor_mode(monitor)

        elif len(monitors) == 1:
            monitor = monitors[0][:monitors[0].find('\t')]
            if monitor.startswith('phy'): monitor = monitors[0].split()[1]
            return self.enable_monitor_mode(monitor)

        print GR + " [+]" + W + " available wireless devices:"
        for i, monitor in enumerate(monitors):
            print "  %s%d%s. %s" % (G, i + 1, W, monitor)

        ri = raw_input(
            GR + " [+]" + W + " select number of device to put into monitor mode (%s1-%d%s): " % (G, len(monitors), W))
        while not ri.isdigit() or int(ri) < 1 or int(ri) > len(monitors):
            ri = raw_input(" [+] select number of device to put into monitor mode (%s1-%d%s): " % (G, len(monitors), W))
        i = int(ri)
        monitor = monitors[i - 1][:monitors[i - 1].find('\t')]
		if monitor.startswith('phy'): monitor = monitors[0].split()[1] <-- yall forgot it here too, fuckin IDIOTS!

        return self.enable_monitor_mode(monitor)

PUT CODE THAT ACTUALLY FUCKIN WORKS IN THE REPO AND DONT BE WASTIN PPLS TIME!!!
