### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Pastafarianist** [derv82/wifite#83]
```
$ sudo wifite -mac

  .;'                     `;,    
 .;'  ,;'             `;,  `;,   WiFite v2 (r85)
.;'  ,;'  ,;'     `;,  `;,  `;,  
::   ::   :   ( )   :   ::   ::  automated wireless auditor
':.  ':.  ':. /_\ ,:'  ,:'  ,:'  
 ':.  ':.    /___\    ,:'  ,:'   designed for Linux
  ':.       /_____\      ,:'     
           /       \             

 [+] mac address anonymizing enabled
     note: only works if device is not already in monitor mode!

 [!] the program cowpatty is not required, but is recommended

 [+] scanning for wireless devices...
 [+] available wireless devices:
  1. PHY        Interface       Driver          Chipset
  2. phy0       wlan1           rt2800usb       D-Link Corp. 
 [+] select number of device to put into monitor mode (1-2): 2
Traceback (most recent call last):
  File "/usr/bin/wifite", line 2966, in <module>
    main()
  File "/usr/bin/wifite", line 251, in main
    iface = get_iface()
  File "/usr/bin/wifite", line 981, in get_iface
    mac_anonymize(monitor)
  File "/usr/bin/wifite", line 1565, in mac_anonymize
    ORIGINAL_IFACE_MAC = (iface, old_mac)
UnboundLocalError: local variable 'old_mac' referenced before assignment
```

**Comment by sevvie** [comment]
Enable monitor mode on your device before starting wifite.py; i.e.

`airmon-ng start wlan1 && wifite.py -mac -aircrack`
